title: "My Recipe Website"
description: "A collection of my favorite recipes"
lang: en
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
collections:
  recipes:
    output: true
    permalink: /recipes/:title/
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache