title: "Sahil Culinary School Portfolio"
description: "I am him"
lang: en
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
skip_to_main_content_link: false
collections:
  recipes:
    output: true
    permalink: /recipes/:title/
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache